name: Destructor
version: ${project.version}
main: net.judgeglass.destructor.Destructor
authors: [HunterWIlcox]
description: An Item Destructor
website: www.judgeglass.net
commands:
  destructor:
    description: Deconstructs Items
    usage: /destructor
